language: python
python:
  - "3.7"
cache: pip

jobs:
  include:
    - name: "code_style_formatting"
      script:
        # Check black formatting would not make any chages
        - black --check */

notifications:  
  email:  
    recipients:  
    - ohamelijnck@gmail.com  
    on_failure: always
