#==============================CLUSTER SETTINGS==============================
local:
  type: 'local'

docker:
  type: 'local'
  #libs to mount
  name: 'defaultobject/deep_kernel:latest'
  libs: [
    '../../libs',
    '~/Documents/projects/model_log/model_log/',  
    '../utils/', 
    'data/'
  ]

orac:
  type: 'cluster'
  modules: [] 
  key:  '~/.ssh/ollie_cluster_rsa'
  user: 'csrcqm'
  host: 'orac.csc.warwick.ac.uk'
  sif: '~/projects/gpjax/gpjax_latest.sif'
  libs: [
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/gpjax/gpjax', 
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/gpjax_utils/gpjax_utils', 
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/Newt/newt/',  
    '/Users/ohamelijnck/Documents/projects/model_log/model_log/', 
    'experiment_config.yaml', 
    '../utils/',
    'setup_data.py'
    ]
  sync: ['models/checkpoints/']
  sbatch:
    time: '07:00:00' 
    mem-per-cpu: 4571
    ntasks-per-node: 8

pearl:
  type: 'cluster'
  modules: [] 
  key:  '~/.ssh/ollie-pearl'
  user: 'pearl053'
  host: 'ui.pearl.scd.stfc.ac.uk'
  sif: '~/projects/gpjax/gpjax_latest.sif'
  libs: [
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/gpjax/gpjax', 
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/gpjax_utils/gpjax_utils', 
    '/Users/ohamelijnck/Documents/projects/ati-fcai/code/libs/Newt/newt', 
    '/Users/ohamelijnck/Documents/projects/model_log/model_log/', 
    'experiment_config.yaml', 
    'setup_data.py', 
    '../utils/'
  ]
  sync: ['models/checkpoints/']
  sbatch:
    time: '07:00:00' 
    cpus: 1
    ntasks: 1
    cpus-per-task: 8
    mem-per-cpu: 32000 #32gb
